# -*- coding: utf-8 -*-
"""gpt-4 vision

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ry3MQ7gqf6cToVrZvoggXi7pvpD959Pq
"""

!pip install --upgrade openai # to update latest OpenAI Python package
import os # Included to Python
from openai import OpenAI # OpenAI official Python package
from IPython.display import Audio

client = OpenAI(api_key='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')
# Presuming 'query' and 'trans' are variables holding parts of your query
query = "The image shows video frames in sequence. Describe what's likely going on in each frame. The video transcription is as follows"

# Concatenate the text parts into one query
query_total = query

# Send the combined query and the image to the API
response = client.chat.completions.create(
    model= "gpt-4",  # This is a placeholder model name
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": query_total},
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://imgur.com/a/k0aVeUA"
                        },
                    },
                ],
            },
    ],
    max_tokens=300
)

# Print the response
print(response)

!pip install --upgrade openai # to update latest OpenAI Python package
import os # Included to Python
from openai import OpenAI # OpenAI official Python package
from IPython.display import Audio

client = OpenAI(api_key='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')


response = client.chat.completions.create(
  model="gpt-4-vision-preview",
  messages=[
    {
      "role": "user",
      "content": [
        {"type": "text", "text": "What’s in this image?"},
        {
          "type": "image_url",
          "image_url": {
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
          },
        },
      ],
    }
  ],
  max_tokens=300,
)

print(response.choices[0])