# -*- coding: utf-8 -*-
"""xboost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d3DqD0aVBcJv7rMeCZoUNApqZzBeqoEm
"""

! rm -rf NBA-Machine-Learning-Sports-Betting
! rm -rf *

#Bootstrap Files
! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! mv -v ./NBA-Machine-Learning-Sports-Betting/* .

#For some reason pip3 install -r requirements.txt doesn't work on Colab
! pip3 install colorama==0.4.6
! pip3 install sbrscrape==0.0.10
! pip3 install pandas==2.1.1
! pip3 install tensorflow==2.14.0
! pip3 install xgboost==2.0.0

import pandas as pd
schedule_df = pd.read_csv('Data/nba-2023-UTC.csv')
schedule_df['Date'] = pd.to_datetime(schedule_df['Date'], format='%d/%m/%Y %H:%M')

!python3 main.py -A -odds=funduel